import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { useState } from "react";
import { BsSearch } from "react-icons/bs";
import { headers } from "@/next.config";
import Weather from "@/components/Weather";
import Spinner from "@/components/Spinner";

export default function Home() {
    const [city, setCity] = useState("");
    const [weather, setWeather] = useState({});
    const [loading, setLoading] = useState(false);

    const url = `http://api.weatherapi.com/v1/current.json?key=${process.env.NEXT_PUBLIC_WEATHER_KEY}&q=${city}&aqi=yes`;

    const fetchWeather = (e) => {
        e.preventDefault();
        const cityName = document.getElementById("city");
        setLoading(true);
        axios
            .get(url, { headers: { "Access-Control-Allow-Origin": "*" } })
            .then((response) => {
                setWeather(response.data);
            });
        setCity("");
        cityName.value = "";
        setLoading(false);
    };

    if (loading) {
        console.log("Loading weather");
        return <Spinner />;
    } else {
        return (
            <div>
                <Head>
                    <title>Wheater Next App</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className="absolute top-0 left-0 right-0 bottom-0 bg-black/35 z-[1]" />
                <Image
                    src="https://images.unsplash.com/photo-1580193769210-b8d1c049a7d9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=874&q=80"
                    layout="fill"
                    className="object-cover"
                />
                <div className="relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 text-white z-10">
                    <form
                        onSubmit={fetchWeather}
                        className="flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl"
                    >
                        <div>
                            <input
                                id="city"
                                onChange={(e) => setCity(e.target.value)}
                                className="bg-transparent border-none text-white focus:outline-none text-2xl placeholder:text-white "
                                type="text"
                                placeholder="Search city..."
                            />
                        </div>
                        <button onClick={fetchWeather}>
                            <BsSearch size={25} />
                        </button>
                    </form>
                </div>

                {/*Weather*/}
                {weather.location && <Weather data={weather} />}
            </div>
        );
    }
}
